server:
  port: 9080

spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8761/eureka}

messaging:
  provider: ${MESSAGING_PROVIDER:kafka}
  destination:
    products: products
  kafka:
    client-id: ${KAFKA_CLIENT_ID:inventory-service}
    topic: ${KAFKA_TOPIC:products}
    group-id: ${KAFKA_GROUP_ID:inventory-service}
    max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1}
  kinesis:
    stream-name: ${KINESIS_STREAM_NAME:products}
    region: ${KINESIS_REGION:us-east-1}
    endpoint-override: ${ENDPOINT_OVERRIDE:http://localhost:4566}
    async-native: ${KINESIS_ASYNC:false}
  pulsar:
    subscription-name: ${PULSAR_SUBSCRIPTION_NAME:inventory-service}

security:
  enabled: ${SECURITY_ENABLED:false}
  jwt:
    secret: ${JWT_SECRET:}
    expiration: ${JWT_EXPIRATION:900000}
  public:
    url:

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: info